packages:
  - .

allowBuilds:
  esbuild: false
  unrs-resolver: false

enablePrePostScripts: false

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - pnpm@11.7.0
  - uuid@14.0.0

overrides:
  '@types/node': ^24

strictPeerDependencies: false
